apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexo-raiden-rabbitmq-secret
  namespace: messaging
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: nexo-raiden-vault
    kind: ClusterSecretStore
  target:
    name: nexo-raiden-rabbitmq-secret
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: messaging/rabbitmq
        property: RABBITMQ_PASSWORD
