apiVersion: v1
kind: Secret
metadata:
  name: nexo-raiden-keycloak-secret
  namespace: platform
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: nexo_password_keycloack_admin
  KC_DB_USERNAME: nexo_admin
  KC_DB_PASSWORD: nexo_password_keycloack
