apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexo-raiden-external-secrets
  namespace: argocd
spec:
  project: nexo-raiden-platform
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.6.0
    helm:
      releaseName: external-secrets
      values: |
        installCRDs: true
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
