apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexo-raiden-external-secrets
  namespace: argocd
spec:
  project: nexo-raiden-platform
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 2.6.0
    helm:
      releaseName: external-secrets
      values: |
        crds: 
          create: true
        certController:
          create: false
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 768Mi
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
