apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexo-raiden-external-secrets-config
  namespace: argocd
spec:
  project: nexo-raiden-platform
  source:
    repoURL: https://github.com/nexoraiden/homelab-gitops.git
    targetRevision: main
    path: infrastructure/security/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
