apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexo-raiden-ingress-nginx
  namespace: argocd
spec:
  project: nexo-raiden-platform
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.3
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
