apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexo-raiden-kube-prometheus-stack
  namespace: argocd
spec:
  project: nexo-raiden-platform
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 66.3.1
    helm:
      releaseName: kube-prometheus-stack
      values: |
        fullnameOverride: nexo-raiden-monitoring

        prometheus:
          prometheusSpec:
            retention: 7d
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 500m
                memory: 1Gi

        grafana:
          enabled: true
          adminPassword: admin
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi

        alertmanager:
          enabled: true
          alertmanagerSpec:
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi

        prometheus-node-exporter:
          enabled: true

        kube-state-metrics:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
