apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexo-raiden-tempo
  namespace: argocd
spec:
  project: nexo-raiden-platform
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.10.3
    helm:
      releaseName: tempo
      values: |
        tempo:
          retention: 24h
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi

        persistence:
          enabled: true
          size: 5Gi
          storageClassName: local-path

        serviceMonitor:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
