apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexo-raiden-vault
  namespace: argocd
spec:
  project: nexo-raiden-platform
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.33.0
    helm:
      releaseName: vault
      values: |
        server:
          standalone:
            enabled: true
          ha:
            enabled: false
          dataStorage:
            enabled: true
            size: 5Gi
            storageClass: local-path
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
        ui:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
