apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: nexo-raiden-vault
spec:
  provider:
    vault:
      server: "http://vault.security.svc.cluster.local:8200"
      path: "nexo"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          namespace: security
          key: token
