apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexo-raiden-test-secret
  namespace: security
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: nexo-raiden-vault
    kind: ClusterSecretStore
  target:
    name: nexo-raiden-test-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: platform/test
        property: username
    - secretKey: password
      remoteRef:
        key: platform/test
        property: password
